MediaBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: MediaBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        utilisateur:
            type: string
            length: 255
        commentaires:
            type: text
    lifecycleCallbacks: {  }

    manyToOne:
        album:
            targetEntity: Album
            inversedBy: commentaires
